apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: dinamicandriy/factor
          name: factor-app
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /livetest
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /livetest
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30